name: FreeBSD
on:
  schedule:
    - cron: '10 9 * * *'
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/FreeBSD.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/FreeBSD.yml'


concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  FreeBSD:
    strategy:
      matrix:
        release: [""]
    runs-on: ubuntu-22.04
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_ACME_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v3
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8080
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" | sed 's/ http:\/\///' >> $GITHUB_ENV
    - uses: vmactions/freebsd-vm@v1
      with:
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server'
        nat: |
          "8080": "80"
        prepare: pkg install -y socat curl
        usesh: true
        release: ${{ matrix.release }}
        copyback: false
        run: ./letest.sh
